### ISSUE TITLE
Update for GazeSDK 4.1.0?

### ISSUE THREAD

**Issue by dddExperiments** [jiahansu/GazeJS#3]
Hi,

I tried to use your node package but it looks like the binding with bridjs need to be update for the latest  version of the gaze sdk?

> [2015-11-15 20:10:26.842] [DEBUG] TobiiGazeImpl - Tobii EyeTracker Model name: t
> et-tcp://127.0.0.1
> [2015-11-15 20:10:26.850] [DEBUG] TobiiGazeImpl - Tobii Gaze SDK version: ...
> Library version: undefined
> Model name: tet-tcp://127.0.0.1
> [2015-11-15 20:10:26.983] [DEBUG] TobiiGazeImpl - runEventLoop++
> [2015-11-15 20:10:26.986] [DEBUG] TobiiGazeImpl - runEventLoop--
> [2015-11-15 20:10:27.000] [DEBUG] TobiiGazeImpl - gaze.runEventLoop() returned

I used: Tobii Gaze SDK C API 4.1.0 Win64 (http://developer.tobii.com/?wpdmdl=131)
Alternatively, can you send me the link of the gaze sdk version that you have been using (4.03)?

Thanks a lot!
--Henri

**Comment by jiahansu** [comment]
Hi, dddExperiments 

This issue is due to the BridJS's behavior changes , not relate to Gaze SDK version, I will release patch today.

Sorry for your inconvenience,

**Comment by jiahansu** [comment]
Fixed in V0.5.000-4
