### ISSUE TITLE
Calibrate Tobii ExeX

### ISSUE THREAD

**Issue by LilyFG** [jiahansu/GazeJS#6]
First I would like to thank you for this package. It is really helpful to be able to integrate my EyeX with my js project. 

I am wondering how I should calibrate the eye tracker. Should I do this from the Tobii software before running my js project, or is there a way to access the calibration procedure from within gazejs. I notice that the calibration file in the Tobii folder is empty.

**Comment by jiahansu** [comment]
Hi, LilyFG

You should calibrate EyeX from Tobii software.
GazeJS only support runtime calibration for EyeLink.
